# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 12:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 30, 12, 28, 17, 300756, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
